### ISSUE TITLE
제주대학교에서 얻어야할 정보

### ISSUE THREAD

**Issue by kimseungdeok** [Jeju-owl/JNU-guide#18]
- [x] 주변 식당 정보
- [x] ATM 위치 정보
- [x] 순환 버스 노선 파악
- [x] 심야 버스 시간표 사진

**Comment by kimseungdeok** [comment]
정문 들어가기전
- 제주 1개
- 농협 1개
본관
- 농협 3개
중앙도서관
- 농협 1개
학생회관
- 농협 1개
학생 생활관 1호관
- 농협 1개

모든 ATM 6시부터 24시 까지

**Comment by kimseungdeok** [comment]
![노선표](https://user-images.githubusercontent.com/81807434/136660104-30a9d12f-a072-4a83-9377-2e4a6ca165aa.png)
참고 : https://lib.jejunu.ac.kr/#/bbs/notice/2755?offset=0&max=20

**Comment by Kimkyeongbeom4844** [comment]
굳굳

**Comment by kimseungdeok** [comment]
![](https://lib.jejunu.ac.kr/pyxis-api/attachments/BULLETIN/a3b0e6ee-2e1a-45fc-8d9b-d1dcc35aa64e)
참고 : https://lib.jejunu.ac.kr/#/bbs/notice/2755?offset=0&max=20
